#!/bin/bash
cd ~/.vim/bundle/ctrlp.vim
printf "ctrlp.vim: "
git pull origin
cd ~/.vim/bundle/nerdtree
printf "nerdtree: "
git pull origin
cd ~/.vim/bundle/syntastic
printf "syntastic: "
git pull origin
